### ISSUE TITLE
Not able to set temp basal >=6.4U/hr in decocare

### ISSUE THREAD

**Issue by TC2013** [bewest/decoding-carelink#116]
As @loudnate explained, "...due to how basal rates are encoded (# of 1/40 U doses) and that 6.4 * 40 = 256, which is the maximum integer that could be communicated with one byte."

**Comment by TC2013** [comment]
Loop/Loopkit users have reported being able to set temp basal rates up to 35.0u/hr.

**Comment by TC2013** [comment]
@ps2 tested with a 722 pump and confirmed Loop is able to set temps up to 34.0u/hr.  He explained that they send two bytes of data for temp basals.

**Comment by ps2** [comment]
Here is how it's done in MinimedKit: https://github.com/ps2/rileylink_ios/blob/dev/MinimedKit/Messages/ChangeTempBasalCarelinkMessageBody.swift#L21

**Comment by ps2** [comment]
Also, reading current temp basal rate supports up to 34U/hr as well:

https://github.com/ps2/rileylink_ios/blob/dev/MinimedKit/Messages/ReadTempBasalCarelinkMessageBody.swift#L35

**Comment by Bender1061** [comment]
So this is why. I ran into this when I tried to change my max rate on my pump from 6 to 7U/h. Which would be most useful since I'm extremely insulin resistant due to the steroids I'm on.

**Comment by scottleibrand** [comment]
@Bender1061 or @TC2013 can you test this fix?  Let us know if you need help installing @ecc1's branch.

**Comment by Bender1061** [comment]
@scottleibrand  yes I could use some help on that. And I'm currently not using Decocare at all. So how would this integrate with my loop?

**Comment by SandraK82** [comment]
~~~@ecc1 @scottleibrand there is still at least one error remaing after >=6.4U fix from @ecc1:
reporting enact/suggested.json
{"temp":"absolute","bg":145,"tick":"+5","eventualBG":141,"snoozeBG":141,"predBGs":{"IOB":[..shortend..],"aCOB":[..shortend..],"COB":..shortend..]},"COB":5,"IOB":3.42,"reason":"COB: 5, Dev: 69, BGI: -6.51, ISF: 21, Target: 80; Eventual BG 141 >= 85, temp 6.325<7.5U/hr","duration":30,"rate":7.5}
rm: cannot remove ‘enact/enacted.json’: No such file or directory
enact/enacted.json  raised  byte must be in range(0, 256)
pump://JSON/set_temp_basal/enact/enacted.json~~~
All is working nicely now. Was missing the `sudo python setup.py develop` to get it working

**Comment by scottleibrand** [comment]
@Bender1061 you can clone the branch and then install it with setup.py develop, similar to how it's done here: https://github.com/openaps/docs/blob/master/scripts/quick-src.sh#L11-L15
