### ISSUE TITLE
Parse Exercise Markers in Pump History

### ISSUE THREAD

**Issue by channemann** [bewest/decoding-carelink#126]
Currently, markers are parsed into meal markers and other:

https://github.com/bewest/decoding-carelink/blob/cff4aea826791244a14727e0e796a1216508718a/decocare/history.py#L236-L252

It would be great to parse out the exercise markers as well, specifically for use in some downstream functionality (see https://github.com/loudnate/openaps-predict/issues/13)

**Comment by bewest** [comment]
Ah, this one looks fixed. :-)  Would still love for @MedtronicDiabetes to confirm.
