### ISSUE TITLE
Uninterpreted 722 pump record

### ISSUE THREAD

**Issue by oskarpearson** [bewest/decoding-carelink#131]
I'm currently encountering an uninterpreted 722 pump record.

The page dump and other items are available at the following urls:
http://www.deckle.co.uk/decoding-carelink/problem-reading-latest-pages-2015-09-19/output-from-openaps-use-pump-iter_pump-30.txt
http://www.deckle.co.uk/decoding-carelink/problem-reading-latest-pages-2015-09-19/log-ReadHistoryData.out
http://www.deckle.co.uk/decoding-carelink/problem-reading-latest-pages-2015-09-19/ReadHistoryData-page-0.data

I'm going to try and see what the official minimed software says the item is shortly. I'll update with a comment here.
##

**Comment by oskarpearson** [comment]
We're pretty sure that this is a Insulin Sensitivity change - we adjusted the sensitivity from 2.5 -> 2 at around 10:45 AM.

**Comment by loudnate** [comment]
Were you able to get the carelink CSV? It's often extremely helpful in finding the contents of the record, as well as knowing what record comes after it.

**Comment by oskarpearson** [comment]
CSV is at http://www.deckle.co.uk/decoding-carelink/problem-reading-latest-pages-2015-09-19/CareLink-Export.csv
