### ISSUE TITLE
Thoughts on adding support for non-carelink interfaces?

### ISSUE THREAD

**Issue by oskarpearson** [bewest/decoding-carelink#135]
Hi

I'm going to be doing a pull request that allows users to use interface methods other than the CareLink. I'm creating this issue for feedback as to how best to restructure things.

At the moment, the ways of linking to a Medtronic device that I know of are:

* https://github.com/bewest/mmblelink (fairly obviously!)
* https://github.com/jberian/mmcommander
* Possibly https://bitbucket.org/atlas0fd00m/rfcat

At the moment there are two key bits that I think would need to change:

1. Explicit references to the serial port ("Link") would need to change, since some interfaces may not be serial (eg: bluetooth).
2. References to a 'Stick' would need to change, since some ways of communicating may not actually be a USB stick - things like the Edison have built in bluetooth.

I'm considering renaming Stick to 'Interface'. I'm also considering removing the references to Link - and instead removing the abstraction of Link vs Stick. The Interface initialisation would need to include a way of addressing things like Bluetooth device IDs.

I would then put the Scan functionality into the Interface code so that the callers don't need to worry about it.

Any suggestions?

Thanks!

**Comment by bewest** [comment]
I think the way to do this is for "new" transports to subclass `Session` correctly, substituting their own "private", per-transport implementations for that transport.

Eg, `mmblelink` and https://github.com/bewest/bayer-medtronic-interface/blob/master/decobayer/link.py will both implement python interfaces that are compatible with what `Session` class does, which should allow re-using all the command module as well as the history decoding implementations.
