### ISSUE TITLE
validate decocare output has required non-zero non-null fields

### ISSUE THREAD

**Issue by scottleibrand** [bewest/decoding-carelink#139]
Per https://github.com/openaps/openaps/issues/32, unvalidated output from decocare (particularly when multiple Carelink sticks are talking to the same pump) can result in incorrect dosing decisions.  To fix this, we want to validate output against the required non-zero non-null fields documented at https://gist.github.com/scottleibrand/da84b4bf799592d19214.

@bewest has created https://github.com/bewest/decoding-carelink/pull/138 to address this.

**Comment by bewest** [comment]
Shipped.  Additional patches welcome.  Closing for now.
