### ISSUE TITLE
Issue reading recent glucose data

### ISSUE THREAD

**Issue by oskarpearson** [bewest/decoding-carelink#173]
pi@pan ~/openaps-source/every-five-standard $ mm-send-comm.py tweak ReadCurGlucosePageNumber
## do stuff with an insulin pump over RF

using `Namespace(autoinit=False, begin=None, bytesPerRecord=None, command='tweak', descr=None, dryrun=False, effectTime=None, end=None, init=False, maxRecords=None, name=None, no_postlude=False, no_prelude=False, no_rf_prelude=False, other='ReadCurGlucosePageNumber', page=None, params=None, port='', postfix=None, prefix=None, prefix_path='', save=False, saveall=False, serial='XXXXX', session_life=10, verbose=None)`

```
```

```
```

```
```

```
```

``` javascript
{'radio': {'errors.crc': 0,
           'errors.naks': 0,
           'errors.sequence': 0,
           'errors.timeouts': 0,
           'packets.received': 15L,
           'packets.transmit': 15L},
 'usb': {'errors.crc': 0,
         'errors.naks': 0,
         'errors.sequence': 0,
         'errors.timeouts': 0,
         'packets.received': 54L,
         'packets.transmit': 54L}}
```

```
```
### PUMP MODEL: `ReadPumpModel:size[64]:data:'722'`

<class 'decocare.commands.ReadCurGlucosePageNumber'> {}
response: ReadCurGlucosePageNumber:size[64]:data:{'isig': 32, 'page': 95L, 'glucose': 32}
hexdump:

``` python
0000   0x00 0x00 0x00 0x5f 0x00 0x20 0x00 0x20    ..._. .
0008   0x00 0x20 0x00 0x20 0x00 0x00 0x00 0x00    . . ....
0010   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0018   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0020   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0028   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0030   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0038   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
```
#### decoded:

``` python
{'isig': 32, 'page': 95L, 'glucose': 32}
```
### end stats

```
```

``` javascript
{'radio': {'errors.crc': 0,
           'errors.naks': 0,
           'errors.sequence': 0,
           'errors.timeouts': 0,
           'packets.received': 17L,
           'packets.transmit': 17L},
 'usb': {'errors.crc': 0,
         'errors.naks': 0,
         'errors.sequence': 0,
         'errors.timeouts': 0,
         'packets.received': 62L,
         'packets.transmit': 62L}}
```

$ mm-send-comm.py tweak ReadGlucoseHistory --save --page 32
## do stuff with an insulin pump over RF

using `Namespace(autoinit=False, begin=None, bytesPerRecord=None, command='tweak', descr=None, dryrun=False, effectTime=None, end=None, init=False, maxRecords=None, name=None, no_postlude=False, no_prelude=False, no_rf_prelude=False, other='ReadGlucoseHistory', page=32, params=None, port='', postfix=None, prefix=None, prefix_path='', save=True, saveall=False, serial='XXXXX', session_life=10, verbose=None)`

```
```

```
```

```
```

```
```

``` javascript
{'radio': {'errors.crc': 0,
           'errors.naks': 0,
           'errors.sequence': 0,
           'errors.timeouts': 0,
           'packets.received': 17L,
           'packets.transmit': 17L},
 'usb': {'errors.crc': 0,
         'errors.naks': 0,
         'errors.sequence': 0,
         'errors.timeouts': 0,
         'packets.received': 67L,
         'packets.transmit': 67L}}
```

```
```
### PUMP MODEL: `ReadPumpModel:size[64]:data:'722'`

<class 'decocare.commands.ReadGlucoseHistory'> {'page': 32}
CRITICAL:decocare.session:this seems like a problem
response: ReadGlucoseHistory:size[1024]:[page][32]:data[2]:
hexdump:

``` python
0000   0x08 0x08                                  ..
```
#### decoded:

``` python
'0000   0x08 0x08                                  ..'
```
### end stats

```
```

``` javascript
{'radio': {'errors.crc': 0,
           'errors.naks': 0,
           'errors.sequence': 0,
           'errors.timeouts': 0,
           'packets.received': 22L,
           'packets.transmit': 22L},
 'usb': {'errors.crc': 0,
         'errors.naks': 0,
         'errors.sequence': 0,
         'errors.timeouts': 0,
         'packets.received': 78L,
         'packets.transmit': 78L}}
```
##

**Comment by bewest** [comment]
* https://github.com/bewest/decoding-carelink/issues/178
* https://github.com/bewest/decoding-carelink/issues/173
* https://github.com/bewest/decoding-carelink/issues/145
