### ISSUE TITLE
Interfacing with decoding-carelink

### ISSUE THREAD

**Issue by erobinson** [bewest/decoding-carelink#30]
From a separate python program what would be the best way to interface with decoding-carelink? Currently I can use the CLI from the other program via os.system(<decoding command>), but I was wondering if there was a better way, such as importing a module and then calling commands.

Thanks.

**Comment by bewest** [comment]
In `decocare.models`, there's now a much much nicer API, see @openaps's `vendors/medtronc.py` for usage examples.

**Comment by bewest** [comment]
Closing this now, see the `decocare.models` api.  Feel free to re-open for questions.
