### ISSUE TITLE
Support Contour Next Link USB in addition to CareLink USB stick

### ISSUE THREAD

**Issue by sulkaharo** [bewest/decoding-carelink#36]
MedTronic just rolled out a new version of CareLink, which supports data uploads using the Contour Next Link USB meter. This device works on USB 3 ports, while the old CareLink stick won't. There's no official word but I'd assume the old CareLink stick is deprecated in favor of Next Link. (The new meter seems to have been on cheap offer lately as well.)

**Comment by bewest** [comment]
Work on contour nextlink is taking place here: https://github.com/bewest/bayer-medtronic-interface

There are some decent usb traces from carelink software here: https://github.com/bewest/decoding-bayer/tree/master/complete-pump-nextlink

In summary, the byte `0xA7` means "this is a pump command."  I don't have a good theory on the byte immediately preceding it, and vigorously welcome testable theories.  Please re-open requests on https://github.com/bewest/bayer-medtronic-interface (this will be a thin wrapper around the `link` and `stick` modules here, and should work with the rest of decocare transparently).
