### ISSUE TITLE
status-quo.sh fails on raspbian

### ISSUE THREAD

**Issue by sulkaharo** [bewest/decoding-carelink#55]
Something in default raspbian setup causes the shell script to blow up and fail to actually run the commands:

bin/common: line 36: time: command not found
bin/common: line 46: time: command not found
bin/common: line 51: time: command not found
bin/common: line 41: time: command not found
bin/common: line 57: time: command not found

**Comment by bewest** [comment]
Ah, this is due to the `time` utility not being available.
I think some people have figured out how to install that utility, hopefully someone will pipe up.

**Comment by kenstack** [comment]
Ugh I remember the problem but not the solution :) I seem to remember it may be a path problem, but it was like a year ago that I ran into that.  Is the utility not installed at all or is it not in the path?

**Comment by codebudo** [comment]
`sudo apt-get install time`

This issue is quite old and has a simple solution. Should it be closed?

**Comment by bewest** [comment]
Thanks!
