### ISSUE TITLE
debugging temp basal commands on 722 vs 723

### ISSUE THREAD

**Issue by kenstack** [bewest/decoding-carelink#58]
based on Ben's earlier suggestions I have given both a 722 and 723 a temp basal - results of list_history.py for the same temp basal for both units are given below.  The command structures look identical to me.  The relevant records are 9,10 for the 722 and 24,25 for the 723.  Please look at this and see what I am missing if anything.  I have a bad feeling they are simply forbidding direct commands since all the query commands work the same but button presses and temp basal do not.

I included the entirety of page 0 for completeness sorry for the length.  One final point - I had to use the larger option on the 723 and the no larger option on the 722 or the 722 was garbage.  There is little history in the 722 since it hasnt been used in a while I am assuming thats why?

The only difference I see is the addition of HOUR BITS line.  But could that be from --larger vs. --no-larger?

722 DATA *******************************

#### STOPPING DOUBLE NULLS @ 208, found 814 nulls
reading more to debug 0x00
    0000   0x00 0x00                                  ..
              0    0
##### DEBUG HEX
    0000   0x86 0xa3                                  ..
##### DEBUG DECIMAL
            134  163
#### RECORD 0 Model522ResultTotals 2014-12-07T00:00:00 head[1], body[41] op[0x6d]

    op hex (1)
    0000   0x6d                                       m
    decimal
            109
    datetime (2014-12-07T00:00:00)
    0000   0xc6 0x0e                                  ..
    body (41)
    hex
    0000   0x05 0x0c 0x00 0xe8 0x00 0x00 0x00 0x00    ........
    0008   0x05 0x8a 0x05 0x8a 0x64 0x00 0x00 0x00    ....d...
    0010   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
    0018   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
    0020   0x00 0x00 0x00 0x0c 0x00 0xe8 0x00 0x00    ........
    0028   0x00                                       .
    decimal
              5   12    0  232    0    0    0    0
              5  138    5  138  100    0    0    0
              0    0    0    0    0    0    0    0
              0    0    0    0    0    0    0    0
              0    0    0   12    0  232    0    0
              0

#### RECORD 1 MResultTotals 2014-12-08T00:00:00 head[5], body[0] op[0x07]

    op hex (5)
    0000   0x07 0x00 0x00 0x05 0x8a                   .....
    decimal
              7    0    0    5  138
    datetime (2014-12-08T00:00:00)
    0000   0xc7 0x0e                                  ..
    body (0)

#### RECORD 2 Model522ResultTotals 2014-12-08T00:00:00 head[1], body[41] op[0x6d]

    op hex (1)
    0000   0x6d                                       m
    decimal
            109
    datetime (2014-12-08T00:00:00)
    0000   0xc7 0x0e                                  ..
    body (41)
    hex
    0000   0x05 0x0c 0x00 0xe8 0x00 0x00 0x00 0x00    ........
    0008   0x05 0x8a 0x05 0x8a 0x64 0x00 0x00 0x00    ....d...
    0010   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
    0018   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
    0020   0x00 0x00 0x00 0x0c 0x00 0xe8 0x00 0x00    ........
    0028   0x00                                       .
    decimal
              5   12    0  232    0    0    0    0
              5  138    5  138  100    0    0    0
              0    0    0    0    0    0    0    0
              0    0    0    0    0    0    0    0
              0    0    0   12    0  232    0    0
              0

#### RECORD 3 MResultTotals 2014-12-09T00:00:00 head[5], body[0] op[0x07]

    op hex (5)
    0000   0x07 0x00 0x00 0x05 0x8a                   .....
    decimal
              7    0    0    5  138
    datetime (2014-12-09T00:00:00)
    0000   0xc8 0x0e                                  ..
    body (0)

#### RECORD 4 Model522ResultTotals 2014-12-09T00:00:00 head[1], body[41] op[0x6d]

    op hex (1)
    0000   0x6d                                       m
    decimal
            109
    datetime (2014-12-09T00:00:00)
    0000   0xc8 0x0e                                  ..
    body (41)
    hex
    0000   0x05 0x0c 0x00 0xe8 0x00 0x00 0x00 0x00    ........
    0008   0x05 0x8a 0x05 0x8a 0x64 0x00 0x00 0x00    ....d...
    0010   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
    0018   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
    0020   0x00 0x00 0x00 0x0c 0x00 0xe8 0x00 0x00    ........
    0028   0x00                                       .
    decimal
              5   12    0  232    0    0    0    0
              5  138    5  138  100    0    0    0
              0    0    0    0    0    0    0    0
              0    0    0    0    0    0    0    0
              0    0    0   12    0  232    0    0
              0

###### DECODED
```python
{'rate': 0.25}
```
    op hex (2)
    0000   0x33 0x0a                                  3.
    decimal
             51   10
    datetime (2014-12-09T21:34:10)
    0000   0xca 0x22 0x15 0x09 0x0e                   ."...
    body (1)
    hex
    0000   0x00                                       .
    decimal
              0
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'duration (min)': 60}
```
    op hex (2)
    0000   0x16 0x02                                  ..
    decimal
             22    2
    datetime (2014-12-09T21:34:10)
    0000   0xca 0x22 0x15 0x09 0x0e                   ."...
    body (0)
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'rate': 0.0}
```
    op hex (2)
    0000   0x33 0x00                                  3.
    decimal
             51    0
    datetime (2014-12-09T21:42:42)
    0000   0xea 0x2a 0x15 0x09 0x0e                   .*...
    body (1)
    hex
    0000   0x00                                       .
    decimal
              0
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'duration (min)': 0}
```
    op hex (2)
    0000   0x16 0x00                                  ..
    decimal
             22    0
    datetime (2014-12-09T21:42:42)
    0000   0xea 0x2a 0x15 0x09 0x0e                   .*...
    body (0)
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'rate': 0.5}
```
    op hex (2)
    0000   0x33 0x14                                  3.
    decimal
             51   20
    datetime (2014-12-09T21:58:02)
    0000   0xc2 0x3a 0x15 0x09 0x0e                   .:...
    body (1)
    hex
    0000   0x00                                       .
    decimal
              0
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'duration (min)': 30}
```
    op hex (2)
    0000   0x16 0x01                                  ..
    decimal
             22    1
    datetime (2014-12-09T21:58:02)
    0000   0xc2 0x3a 0x15 0x09 0x0e                   .:...
    body (0)
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'rate': 0.0}
```
    op hex (2)
    0000   0x33 0x00                                  3.
    decimal
             51    0
    datetime (2014-12-09T21:58:08)
    0000   0xc8 0x3a 0x15 0x09 0x0e                   .:...
    body (1)
    hex
    0000   0x00                                       .
    decimal
              0
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'duration (min)': 0}
```
    op hex (2)
    0000   0x16 0x00                                  ..
    decimal
             22    0
    datetime (2014-12-09T21:58:08)
    0000   0xc8 0x3a 0x15 0x09 0x0e                   .:...
    body (0)
    HOUR BITS: [0, 0, 1]
`end ReadHistoryData-page-0.data: 13 records`

723 DATA********************

#### STOPPING DOUBLE NULLS @ 304, found 718 nulls
reading more to debug 0x00
    0000   0x00 0x00                                  ..
              0    0
##### DEBUG HEX
    0000   0x19 0xed                                  ..
##### DEBUG DECIMAL
             25  237
###### DECODED
```python
{'bg': 0,
 'bg_target_high': 87,
 'bg_target_low': 110,
 'bolus_estimate': 0.0,
 'carb_input': 0,
 'carb_ratio': 11.0,
 'correction_estimate': 0.0,
 'food_estimate': 0.0,
 'sensitivity': 53,
 'unabsorbed_insulin_total': 0.0}
```
    op hex (2)
    0000   0x5b 0x00                                  [.
    decimal
             91    0
    datetime (2014-12-09T19:23:09)
    0000   0xc9 0x17 0x13 0x09 0x0e                   .....
    body (15)
    hex
    0000   0x00 0x50 0x00 0x57 0x35 0x6e 0x00 0x00    .P.W5n..
    0008   0x00 0x00 0x00 0x00 0x00 0x00 0x6e         ......n
    decimal
              0   80    0   87   53  110    0    0
              0    0    0    0    0    0  110

###### DECODED
```python
[{'age': 169, 'amount': 2.9, 'curve': 5},
 {'age': 133, 'amount': 6.3, 'curve': 21}]
```
    op hex (8)
    0000   0x5c 0x08 0x74 0xa9 0x05 0xfc 0x85 0x15    \.t.....
    decimal
             92    8  116  169    5  252  133   21
    datetime (unknown)

    body (0)

###### DECODED
```python
{'amount': 0.4,
 'duration': 0,
 'programmed': 0.4,
 'type': 'normal',
 'unabsorbed': 2.0}
```
    op hex (8)
    0000   0x01 0x00 0x10 0x00 0x10 0x00 0x50 0x00    ......P.
    decimal
              1    0   16    0   16    0   80    0
    datetime (2014-12-09T19:23:09)
    0000   0xc9 0x17 0x33 0x09 0x0e                   ..3..
    body (0)

###### DECODED
```python
{'bg': 0,
 'bg_target_high': 87,
 'bg_target_low': 110,
 'bolus_estimate': 0.0,
 'carb_input': 0,
 'carb_ratio': 11.0,
 'correction_estimate': 0.0,
 'food_estimate': 0.0,
 'sensitivity': 53,
 'unabsorbed_insulin_total': 0.0}
```
    op hex (2)
    0000   0x5b 0x00                                  [.
    decimal
             91    0
    datetime (2014-12-09T19:23:50)
    0000   0xf2 0x17 0x13 0x09 0x0e                   .....
    body (15)
    hex
    0000   0x00 0x50 0x00 0x57 0x35 0x6e 0x00 0x00    .P.W5n..
    0008   0x00 0x00 0x00 0x00 0x00 0x00 0x6e         ......n
    decimal
              0   80    0   87   53  110    0    0
              0    0    0    0    0    0  110

###### DECODED
```python
[{'age': 9, 'amount': 0.4, 'curve': 4},
 {'age': 169, 'amount': 2.9, 'curve': 5},
 {'age': 133, 'amount': 6.3, 'curve': 21}]
```
    op hex (11)
    0000   0x5c 0x0b 0x10 0x09 0x04 0x74 0xa9 0x05    \....t..
    0008   0xfc 0x85 0x15                             ...
    decimal
             92   11   16    9    4  116  169    5
            252  133   21
    datetime (unknown)

    body (0)

###### DECODED
```python
{'amount': 0.3,
 'duration': 0,
 'programmed': 0.3,
 'type': 'normal',
 'unabsorbed': 2.4}
```
    op hex (8)
    0000   0x01 0x00 0x0c 0x00 0x0c 0x00 0x60 0x00    ......`.
    decimal
              1    0   12    0   12    0   96    0
    datetime (2014-12-09T19:23:50)
    0000   0xf2 0x17 0x33 0x09 0x0e                   ..3..
    body (0)

###### DECODED
```python
{'offset': 73800000, 'rate': 1.35}
```
    op hex (2)
    0000   0x7b 0x09                                  {.
    decimal
            123    9
    datetime (2014-12-09T20:30:00)
    0000   0xc0 0x1e 0x14 0x09 0x0e                   .....
    body (3)
    hex
    0000   0x29 0x36 0x00                             )6.
    decimal
             41   54    0

###### DECODED
```python
{'amount': 182}
```
    op hex (2)
    0000   0x0a 0xb6                                  ..
    decimal
             10  182
    datetime (2014-12-09T20:56:16)
    0000   0xd0 0x38 0x34 0x09 0x0e                   .84..
    body (0)
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'bg': 182,
 'bg_target_high': 87,
 'bg_target_low': 110,
 'bolus_estimate': 0.8,
 'carb_input': 0,
 'carb_ratio': 11.0,
 'correction_estimate': 1.3,
 'food_estimate': 0.0,
 'sensitivity': 53,
 'unabsorbed_insulin_total': 0.5}
```
    op hex (2)
    0000   0x5b 0xb6                                  [.
    decimal
             91  182
    datetime (2014-12-09T20:56:29)
    0000   0xdd 0x38 0x14 0x09 0x0e                   .8...
    body (15)
    hex
    0000   0x00 0x50 0x00 0x57 0x35 0x6e 0x34 0x00    .P.W5n4.
    0008   0x00 0x00 0x00 0x14 0x00 0x20 0x6e         ..... n
    decimal
              0   80    0   87   53  110   52    0
              0    0    0   20    0   32  110
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
[{'age': 92, 'amount': 0.175, 'curve': 4},
 {'age': 102, 'amount': 0.525, 'curve': 4},
 {'age': 6, 'amount': 2.9, 'curve': 21}]
```
    op hex (11)
    0000   0x5c 0x0b 0x07 0x5c 0x04 0x15 0x66 0x04    \..\..f.
    0008   0x74 0x06 0x15                             t..
    decimal
             92   11    7   92    4   21  102    4
            116    6   21
    datetime (unknown)

    body (0)

###### DECODED
```python
{'amount': 1.0,
 'duration': 0,
 'programmed': 1.0,
 'type': 'normal',
 'unabsorbed': 0.5}
```
    op hex (8)
    0000   0x01 0x00 0x28 0x00 0x28 0x00 0x14 0x00    ..(.(...
    decimal
              1    0   40    0   40    0   20    0
    datetime (2014-12-09T20:56:29)
    0000   0xdd 0x38 0x34 0x09 0x0e                   .84..
    body (0)
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'amount': 0.3,
 'duration': 0,
 'programmed': 0.3,
 'type': 'normal',
 'unabsorbed': 1.3}
```
    op hex (8)
    0000   0x01 0x00 0x0c 0x00 0x0c 0x00 0x34 0x00    ......4.
    decimal
              1    0   12    0   12    0   52    0
    datetime (2014-12-09T21:26:20)
    0000   0xd4 0x1a 0x35 0x69 0x0e                   ..5i.
    body (0)
    DAY BITS: [0, 1, 1]
#### RECORD 12 Base (2014, 12, 9, 21, 28, 29) head[2], body[0] op[0x62]

    op hex (2)
    0000   0x62 0x00                                  b.
    decimal
             98    0
    datetime ((2014, 12, 9, 21, 28, 29))
    0000   0xdd 0x1c 0x15 0x09 0x0e                   .....
    body (0)

###### DECODED
```python
{'rate': 0.325}
```
    op hex (2)
    0000   0x33 0x0d                                  3.
    decimal
             51   13
    datetime (2014-12-09T21:32:04)
    0000   0xc4 0x20 0x15 0x49 0x0e                   . .I.
    body (1)
    hex
    0000   0x00                                       .
    decimal
              0
    HOUR BITS: [0, 0, 1] DAY BITS: [0, 1, 0]
###### DECODED
```python
{'duration (min)': 30}
```
    op hex (2)
    0000   0x16 0x01                                  ..
    decimal
             22    1
    datetime (2014-12-09T21:32:04)
    0000   0xc4 0x20 0x15 0x49 0x0e                   . .I.
    body (0)
    HOUR BITS: [0, 0, 1] DAY BITS: [0, 1, 0]
###### DECODED
```python
{'rate': 0.0}
```
    op hex (2)
    0000   0x33 0x00                                  3.
    decimal
             51    0
    datetime (2014-12-09T21:32:24)
    0000   0xd8 0x20 0x15 0x09 0x0e                   . ...
    body (1)
    hex
    0000   0x00                                       .
    decimal
              0
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'duration (min)': 0}
```
    op hex (2)
    0000   0x16 0x00                                  ..
    decimal
             22    0
    datetime (2014-12-09T21:32:24)
    0000   0xd8 0x20 0x15 0x09 0x0e                   . ...
    body (0)
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'offset': 73800000, 'rate': 1.35}
```
    op hex (2)
    0000   0x7b 0x09                                  {.
    decimal
            123    9
    datetime (2014-12-09T21:32:24)
    0000   0xd8 0x20 0x15 0x09 0x0e                   . ...
    body (3)
    hex
    0000   0x29 0x36 0x00                             )6.
    decimal
             41   54    0
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'rate': 0.25}
```
    op hex (2)
    0000   0x33 0x0a                                  3.
    decimal
             51   10
    datetime (2014-12-09T21:33:55)
    0000   0xf7 0x21 0x15 0x09 0x0e                   .!...
    body (1)
    hex
    0000   0x00                                       .
    decimal
              0
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'duration (min)': 60}
```
    op hex (2)
    0000   0x16 0x02                                  ..
    decimal
             22    2
    datetime (2014-12-09T21:33:55)
    0000   0xf7 0x21 0x15 0x09 0x0e                   .!...
    body (0)
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'rate': 0.0}
```
    op hex (2)
    0000   0x33 0x00                                  3.
    decimal
             51    0
    datetime (2014-12-09T21:36:18)
    0000   0xd2 0x24 0x15 0x09 0x0e                   .$...
    body (1)
    hex
    0000   0x00                                       .
    decimal
              0
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'duration (min)': 0}
```
    op hex (2)
    0000   0x16 0x00                                  ..
    decimal
             22    0
    datetime (2014-12-09T21:36:18)
    0000   0xd2 0x24 0x15 0x09 0x0e                   .$...
    body (0)
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'offset': 73800000, 'rate': 1.35}
```
    op hex (2)
    0000   0x7b 0x09                                  {.
    decimal
            123    9
    datetime (2014-12-09T21:36:18)
    0000   0xd2 0x24 0x15 0x09 0x0e                   .$...
    body (3)
    hex
    0000   0x29 0x36 0x00                             )6.
    decimal
             41   54    0
    HOUR BITS: [0, 0, 1]
###### DECODED
```python
{'offset': 79200000, 'rate': 1.4000000000000001}
```
    op hex (2)
    0000   0x7b 0x0a                                  {.
    decimal
            123   10
    datetime (2014-12-09T22:00:00)
    0000   0xc0 0x00 0x16 0x09 0x0e                   .....
    body (3)
    hex
    0000   0x2c 0x38 0x00                             ,8.
    decimal
             44   56    0

###### DECODED
```python
{'rate': 0.5}
```
    op hex (2)
    0000   0x33 0x14                                  3.
    decimal
             51   20
    datetime (2014-12-09T22:01:23)
    0000   0xd7 0x01 0x16 0x09 0x0e                   .....
    body (1)
    hex
    0000   0x00                                       .
    decimal
              0

###### DECODED
```python
{'duration (min)': 30}
```
    op hex (2)
    0000   0x16 0x01                                  ..
    decimal
             22    1
    datetime (2014-12-09T22:01:23)
    0000   0xd7 0x01 0x16 0x09 0x0e                   .....
    body (0)

###### DECODED
```python
{'rate': 0.0}
```
    op hex (2)
    0000   0x33 0x00                                  3.
    decimal
             51    0
    datetime (2014-12-09T22:01:32)
    0000   0xe0 0x01 0x16 0x09 0x0e                   .....
    body (1)
    hex
    0000   0x00                                       .
    decimal
              0

###### DECODED
```python
{'duration (min)': 0}
```
    op hex (2)
    0000   0x16 0x00                                  ..
    decimal
             22    0
    datetime (2014-12-09T22:01:32)
    0000   0xe0 0x01 0x16 0x09 0x0e                   .....
    body (0)

###### DECODED
```python
{'offset': 79200000, 'rate': 1.4000000000000001}
```
    op hex (2)
    0000   0x7b 0x0a                                  {.
    decimal
            123   10
    datetime (2014-12-09T22:01:32)
    0000   0xe0 0x01 0x16 0x09 0x0e                   .....
    body (3)
    hex
    0000   0x2c 0x38 0x00                             ,8.
    decimal
             44   56    0

`end ReadHistoryData-page-0.data: 29 records`

**Comment by bewest** [comment]
In general, `--larger` is required for everything bigger than `MX22`.  This would include `MX23` and everything above.   Otherwise, for `MX22` and below, sans that switch.

If button presses do not work and it's a USA model `MX23` or above, it appears temp basal and other key press commands/"write commands" will not work.  If it's a European model and has supporting firmware, the key press commands are the most useful way to tell if it's working.  If key press commands work but temp basal does not, double check that "absolute/rate" type of temp basal is active, rather than percentage type.

Looks like your 523 is a USA model with the commands stripped out. :crying_cat_face: :panda_face: 
See https://github.com/bewest/decoding-carelink/issues/71 for more initiatives on building up the needed folk-lore/documentation.

**Comment by bewest** [comment]
`HOUR_BITS` and `DAY_BITS` are poor attempts to examine extra/unused bits in the datetime segment.

There's certain information about "why" a pump operation was carried out: was it a button press, RF command?  I believe there is a bit somewhere in the date to encode this information, and there may be additional information as well.  The `HOUR_BITS` and `DAY_BITS` should probably be ignored/removed.

**Comment by loudnate** [comment]
The x23 models (running 2.5A) don't accept the button press or temp basal
commands, but they do a "PC Connect" menu that, when active, claims to
support "Change Settings" with the message "Your pump is now ready to
receive changes".

Has anyone tried sending commands in that mode? I will do my own tests
later this week.

**Comment by bewest** [comment]
That is fascinating.... there are a few commands that seem to be associated with that... "begin command settings" and "end command settings" from the paradigmpal software.

**Comment by bewest** [comment]
```

./ddms/deviceportreader/MM512$Command.java:158:        MedicalDevice.logInfoMedium(this, "sendCommand: SENDING CMD " + this + "for pump #" + MM512.this.m_serialNumber);
./ddms/deviceportreader/MM512.java:24:    private static final int CMD_POWER_CTRL = 93;
./ddms/deviceportreader/MM512.java:25:    private static final int CMD_BEGIN_PARAMETER_SETTING = 38;
./ddms/deviceportreader/MM512.java:26:    private static final int CMD_END_PARAMETER_SETTING = 39;
./ddms/deviceportreader/MM512.java:27:    private static final int CMD_TEMP_BASAL_RATE = 76;
./ddms/deviceportreader/MM512.java:28:    private static final int CMD_READ_ERROR_STATUS = 117;
./ddms/deviceportreader/MM512.java:29:    private static final int CMD_READ_FIRMWARE_VER = 116;
./ddms/deviceportreader/MM512.java:30:    private static final int CMD_READ_PUMP_ID = 113;
./ddms/deviceportreader/MM512.java:31:    private static final int CMD_READ_PUMP_STATE = 131;
./ddms/deviceportreader/MM512.java:32:    private static final int CMD_READ_REMOTE_CTRL_IDS = 118;
./ddms/deviceportreader/MM512.java:33:    private static final int CMD_READ_TEMP_BASAL = 152;
./ddms/deviceportreader/MM512.java:34:    private static final int CMD_READ_RTC = 112;
./ddms/deviceportreader/MM512.java:35:    private static final int CMD_SET_RF_REMOTE_ID = 81;
./ddms/deviceportreader/MM512.java:36:    private static final int CMD_SET_ALERT_TYPE = 84;
./ddms/deviceportreader/MM512.java:37:    private static final int CMD_SET_AUTO_OFF = 78;
./ddms/deviceportreader/MM512.java:38:    private static final int CMD_SET_BLOCK_ENABLE = 82;
./ddms/deviceportreader/MM512.java:39:    private static final int CMD_SET_CURRENT_PATTERN = 74;
./ddms/deviceportreader/MM512.java:40:    private static final int CMD_SET_EASY_BOLUS_ENABLE = 79;
./ddms/deviceportreader/MM512.java:41:    private static final int CMD_SET_MAX_BOLUS = 65;
./ddms/deviceportreader/MM512.java:42:    private static final int CMD_SET_PATTERNS_ENABLE = 85;
./ddms/deviceportreader/MM512.java:43:    private static final int CMD_SET_RF_ENABLE = 87;
./ddms/deviceportreader/MM512.java:44:    private static final int CMD_SET_RTC = 64;
./ddms/deviceportreader/MM512.java:45:    private static final int CMD_SET_TIME_FORMAT = 92;
./ddms/deviceportreader/MM512.java:46:    private static final int CMD_SET_VAR_BOLUS_ENABLE = 69;
```

From https://github.com/bewest/decoding-carelink/issues/67

Closing this one for now, #71 is for community meta-discussion on how we should start organizing these details better.  Clearly, there are number of things worth discussing here, the PC Connect thing sounds awesome, but is now buried deep inside an unrelated thread.

**Comment by scottleibrand** [comment]
Nathan,

Yes, "PC Connect" does put a 523 into full read/write mode temporarily, and
you can issue basal and bolus commands.  Unfortunately that mode times out
after a couple minutes, and there's no way I can find to extend it, so it's
not very useful in practice.

-Scott

**Comment by bewest** [comment]
There may be way to use RF to put it into PC mode, there are many commands,
but the true full list is fractured, incomplete.

-bewest

**Comment by bewest** [comment]
I'm curious about this pc mode.

There are two RF commands I see, called  BEGIN_PARAMETER_SETTING (38), and
END_PARAMETER_SETTING (39).

This may be a lot to ask; would it be possible to run these steps?

* a no-op bolus wizard (to start "logging our experiment")
* put in PC Mode
* issue temp basal, cancel issue (2x)
* end PC mode/or let it time out
* run another no-op bolus wizard (to end "logging our experiment")
* Take first page of data, eg using mm-send-comm.py --init tweak --save
ReadHistoryData --page 0

Send page of data to me, preferably the data file.  Ideally with carelink
csv.

If I can verify that manipulating these BEGIN/END parameter setting
commands create similar records in the history files, then it should be
possible to create a tool that can use this to issue the needed commands as
a workaround.

-bewest

**Comment by loudnate** [comment]
Ran through this tonight, @bewest, but I couldn't send the temp basals from decocare:

`root@nater:~/src/github.com/bewest/decoding-carelink/bin# ./mm-temp-basals.py --serial $SERIAL --port /dev/ttyUSB0 --duration 5 --rate 1 set`
## do stuff with an insulin pump over RF
using ` Namespace(autoinit=False, command='set', dryrun=False, duration=5, init=False, no_postlude=False, no_prelude=False, no_rf_prelude=False, out=<open file '<stdout>', mode 'w' at 0x7fcec0cd31e0>, port='/dev/ttyUSB0', rate=1.0, serial='736868', session_life=10, verbose=None) `
```
```
```
```
```
```
```
```
```javascript
{'radio': {'errors.crc': 0,
           'errors.naks': 0,
           'errors.sequence': 0,
           'errors.timeouts': 6,
           'packets.received': 3L,
           'packets.transmit': 9L},
 'usb': {'errors.crc': 0,
         'errors.naks': 3,
         'errors.sequence': 0,
         'errors.timeouts': 0,
         'packets.received': 252L,
         'packets.transmit': 255L}}
```
```
```
### PUMP MODEL: `ReadPumpModel:size[64]:data:'523'`
response: ReadBasalTemp:size[64]:data:{'duration': 0, 'rate': 1.3}
#### decoded:
```python
{'duration': 0, 'rate': 1.3}
```
CRITICAL:decocare.session:this seems like a problem
response: TempBasal:size[64]:data:bytearray(b'\x08')
hexdump:
```python
0000   0x08                                       .
```
#### decoded:
```python
bytearray(b'\x08')
```
response: ReadBasalTemp:size[64]:data:{'duration': 0, 'rate': 1.3}
#### decoded:
```python
{'duration': 0, 'rate': 1.3}
```
{
  "duration": 0, 
  "rate": 1.3
}### end stats
```
```
```javascript
{'radio': {'errors.crc': 0,
           'errors.naks': 0,
           'errors.sequence': 0,
           'errors.timeouts': 6,
           'packets.received': 8L,
           'packets.transmit': 14L},
 'usb': {'errors.crc': 0,
         'errors.naks': 3,
         'errors.sequence': 0,
         'errors.timeouts': 0,
         'packets.received': 266L,
         'packets.transmit': 269L}}
```

**Comment by scottleibrand** [comment]
Did you successfully get the pump into "PC connect" "Change Settings" mode?

-Scott

**Comment by loudnate** [comment]
@scottleibrand I did. The output above only occurs while the pump is in the "CHANGE SETTINGS" screen. Otherwise, the `TempBasal` command fails with 
```
WARNING:decocare.stick:Stick transmit[TransmitPacket:TempBasal:data:unknown] reader[ReadRadio:size:14] download_i[5] status[<LinkStatus:0x03:status:size=??LinkStatus:error:True:reason:[]:size(0)>] poll_size[0] poll_i[False] command[<LinkStatus:0x03:status:size=??LinkStatus:error:True:reason:[]:size(0)>]:download(attempts[5],expect[0],results[0]:data[0]):BAD AILING
```

**Comment by loudnate** [comment]
So the issue I had here was that my pump was configured for percentage-based temp basals. PR forthcoming with the requested history data.
