### ISSUE TITLE
Calling mm-latest.py as a module

### ISSUE THREAD

**Issue by scottleibrand** [bewest/decoding-carelink#77]
This is mostly just python ignorance, but is it possible for me to somehow include mm-latest.py as a module, so I can call all the functions in it from my own script?

**Comment by scottleibrand** [comment]
Ah, figured it out.  Module imports apparently can't have -'s in them, so I just had to rename mm-latest.py to mmlatest.py and import mmlatest.

**Comment by bewest** [comment]
That's true, but I put a hyphen in the name because it's not designed to be imported for re-use, it was designed as an "example application" of decocare.
