### ISSUE TITLE
Include insert.sh as a pypi script?

### ISSUE THREAD

**Issue by loudnate** [bewest/decoding-carelink#93]
The contents of insert.sh need to be run by decocare clients, e.g. openaps.

**Comment by bewest** [comment]
Try `sudo openaps-install-udev-rules`?  I put the contents of `insert.sh` into the udev rule.

**Comment by bewest** [comment]
Not hard to do though, might as well.

**Comment by loudnate** [comment]
You're right, I was running that in the container, but it belongs on the host. Thanks!

**Comment by loudnate** [comment]
Updated the docker instructions to reflect the installing the udev rules: https://gist.github.com/loudnate/e70a2a578ec87e2d17f6

**Comment by bewest** [comment]
That's cool.
