### ISSUE TITLE
ReadCarbRatios512 returning incorrect data for MM522

### ISSUE THREAD

**Issue by loudnate** [bewest/decoding-carelink#98]
```python
{
    "i": 10,  # Actual ratio value
    "x": 0,  # 0-based index
    "r": 23,  # Actual offset value for the next record, in 30 minute increments
    "ratio": 23,  # Actual offset value for the next record, in 30 minute increments
    "offset": 300  # i * 30 (not useful)
},
```

**Comment by bewest** [comment]
Ouch... is this still wrong, should probably be fixed for next release.

**Comment by loudnate** [comment]
Yeah I filed this as a reminder, I'm happy to commit a fix. If you know any
individuals with earlier models than a 522 (which I have) that can help
test this, feel free to tag them here!

**Comment by scottleibrand** [comment]
I have a 515.

-Scott

**Comment by bewest** [comment]
This is for 512 only?

**Comment by bewest** [comment]
I just tried a patch to get towards this in https://github.com/bewest/decoding-carelink/pull/103.  Basically had those two values backwards, it looks like?

**Comment by bewest** [comment]
Oh, are you saying there's also off by one error, causing mismatch?  Is there any option to set grams vs exchanges?
